name: Maven CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, feature/INT-1  ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run:  mvn -B package --file pom.xml

      # SonarCloud
      - name: SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=SofijaDjordjevic_IROIT-Grupa-5 \
            -Dsonar.organization=sofijadjordjevic \
            -Dsonar.host.url=https://sonarcloud.io
          

      - name: Test Report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: SpringBoot Report
          path: target/surefire-reports/



      #  Build Docker image
      - name: Build Docker image
        run: docker build -t bookstore-app .

      # Run container to test
      - name: Run Docker container
        run: docker run -d -p 8088:8088 --name test-container bookstore-app

      # Stop and remove container
      - name: Stop Docker container
        run: docker stop test-container && docker rm test-container


      # Docker Compose
      - name: Build and start containers
        run: docker compose up -d --build

      - name: Wait for services
        run: sleep 30

      - name: Show container status
        run: docker compose ps

      - name: Stop containers
        if: always()
        run: docker compose down